---
  apiVersion: "apps/v1"
  kind: "Deployment"
  metadata: 
    name: "monolith"
    labels: 
      app: "monolith"
  spec: 
    selector: 
      matchLabels: 
        app: "monolith"
    replicas: 1
    template: 
      metadata: 
        labels: 
          app: "monolith"
      spec: 
        containers: 
          - 
            name: "monolith"
            image: "monolith"
            ports: 
              - 
                containerPort: 8080
            readinessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 10
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 10
            livenessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 120
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 5
---
  apiVersion: "v1"
  kind: "Service"
  metadata: 
    name: "monolith"
    labels: 
      app: "monolith"
  spec: 
    ports: 
      - 
        port: 8080
        targetPort: 8080
    selector: 
      app: "monolith"
---
  apiVersion: "apps/v1"
  kind: "Deployment"
  metadata: 
    name: "boundedcontext940"
    labels: 
      app: "boundedcontext940"
  spec: 
    selector: 
      matchLabels: 
        app: "boundedcontext940"
    replicas: 1
    template: 
      metadata: 
        labels: 
          app: "boundedcontext940"
      spec: 
        containers: 
          - 
            name: "boundedcontext940"
            image: "boundedcontext940"
            ports: 
              - 
                containerPort: 8080
            readinessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 10
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 10
            livenessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 120
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 5
---
  apiVersion: "v1"
  kind: "Service"
  metadata: 
    name: "boundedcontext940"
    labels: 
      app: "boundedcontext940"
  spec: 
    ports: 
      - 
        port: 8080
        targetPort: 8080
    selector: 
      app: "boundedcontext940"
